@baseURL = http://localhost:3000/public

### POST de Institucion
POST {{baseURL}}/institucion/
Content-Type: application/json
Accept: application/json

{
  "nombreinstitucion": "Universidad XYZ",
  "reseniainstitucion": "Una breve descripción de la universidad.",
  "logoinstitucion": null,
  "nombrecontacto": "Juan Pérez",
  "correocontacto": "juan.perez@univez.com",
  "celularcontacto": "12345678",
  "usuario": {
    "id": 1
  },
  "sectorpertenencia": {
    "id": 3
  }
}

### POST de Estudiante
POST {{baseURL}}/estudiante/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImVtYWlsIjoicXVpc3Blb3N2YWxkbzMxQGdtYWlsLmNvbTIiLCJpYXQiOjE3MDA0NTA5MjUsImV4cCI6MTcwMDQ1NDUyNX0.FiLnKHXguXMDzxum0z9O12HJf3MmKLIAGmSNCPuLy1Y

{
  "usuario_id": 3,
  "nombres": "Juan2",
  "apellidos": "Péreza",
  "carnetidentidad": "12345678912",
  "correoelectronico": "juan.perez@email.com2",
  "celularcontacto": "555-555-5555",
  "graduado": true,
  "carrera": { "id": 1 },
  "semestre": { "id": 1 },
  "sede": { "id": 1 },
  "aniograduacion": 2022,
  "linkcurriculumvitae": "http://example.com/juan_perez_cv.pdf"
}
### Envío de correo electrónico
POST {{baseURL}}/sendEmail
Accept: application/json
Content-Type: application/json

{
  "email": "quispeosvaldo31@gmail.com"
}



### Verificar el codigo de verificacion
POST {{baseURL}}/validateCode
Accept: application/json
Content-Type: application/json

{
  "email": "junito11@ucb.edu.bo",
  "code": "123456"
}
