@baseURL = http://localhost:3000/adminUSEI

### GET ALL USEI ADMINS 
GET {{baseURL}}/
Accept: application/json

### GET USEI ADMIN BY ID
GET {{baseURL}}/5
Accept: application/json

### POST A NEW USEI ADMIN
POST {{baseURL}}/
Accept: application/json
Content-Type: application/json

{
    "usuario": {
        "id": 6
    }
}

### PUT A USEI ADMIN DATA
PUT {{baseURL}}/9
Accept: application/json
Content-Type: application/json

{
    "usuario": {
        "id": 7
    }
}

### DELETE A USEI ADMIN
DELETE {{baseURL}}/5
Accept: application/json