@base_url = http://localhost:3000/auth

### Inicio de Sesión
POST {{base_url}}/login
Content-Type: application/json
Accept: application/json

{
  "idusuario": "estudiante1",
  "password": "estudiante1"
}

### Cierre de Sesión
GET {{base_url}}/logout
Accept: application/json

### Verificar Estado de Autenticación
GET {{base_url}}/status
Accept: application/json
