@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

### GET ALL Comentarios
GET http://{{host}}/comentarioconvocatoria/
Accept: application/json

### GET Comentario by ID
GET http://{{host}}/comentarioconvocatoria/1
Accept: application/json

### POST Comentario
POST http://{{host}}/comentarioconvocatoria/
Content-Type: application/json
Accept: application/json

{
  "comentario": "Este es un comentario de prueba",
  "puntuacion": 4,
  "postulacion": {
    "id": 1
  },
  "convocatoria": {
    "id": 2
  }
}

### PUT Comentario
PUT http://{{host}}/comentarioconvocatoria/2
Content-Type: application/json
Accept: application/json

{
  "comentario": "Comentario actualizado",
  "puntuacion": 5,
  "postulacion": {
    "id": 1
  },
  "convocatoria": {
    "id": 3
  }
}

### DELETE Comentario
DELETE http://{{host}}/comentarioconvocatoria/2
Accept: application/json
