@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

### GET ALL Convocatorias
GET http://{{host}}/convocatoria/
Accept: application/json

### GET Convocatoria by ID
GET http://{{host}}/convocatoria/7
Accept: application/json

### POST Convocatoria
POST http://{{host}}/convocatoria/
Content-Type: application/json
Accept: application/json

{
  "areapasantia": "Área de prueba",
  "descripcionfunciones": "Descripción de funciones",
  "requisitoscompetencias": "Requisitos y competencias",
  "horario_inicio": "08:00",
  "horario_fin": "17:00",
  "fechasolicitud": "2023-10-22",
  "fechaseleccionpasante": "2025-12-12",
  "estadoconvocatoria": {
    "id": 2
  },
  "institucion": {
    "id": 1
  },
  "tiempoacumplir": {
    "id": 2
  }
}

### PUT Convocatoria
PUT http://{{host}}/convocatoria/8
Content-Type: application/json
Accept: application/json

{
  "areapasantia": "Area actualizada",
  "descripcionfunciones": "Descripción actualizada",
  "requisitoscompetencias": "Requisitos y competencias",
  "horario_inicio": "08:00",
  "horario_fin": "17:00",
  "fechasolicitud": "2023-10-22",
  "fechaseleccionpasante": "2025-12-12",
  "estadoconvocatoria": {
    "id": 2
  },
  "institucion": {
    "id": 1
  },
  "tiempoacumplir": {
    "id": 2
  }
}


### DELETE Convocatoria
DELETE http://{{host}}/convocatoria/18
Accept: application/json
