@hostname = localhost
@port = 3000
@host = http://{{hostname}}:{{port}}

### Obtener todos los registros históricos
GET {{host}}/historicoPostulaciones

### Obtener un registro histórico por ID
GET {{host}}/historicoPostulaciones/1

