@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

### GET ALL de Institucion
GET http://{{host}}/institucion/
Accept: application/json

### GET de Institucion por ID
GET http://{{host}}/institucion/2
Accept: application/json

### POST de Institucion
POST http://{{host}}/institucion/
Content-Type: application/json
Accept: application/json

{
  "nombreinstitucion": "Universidad XYZ",
  "reseniainstitucion": "Una breve descripción de la universidad.",
  "logoinstitucion": null,
  "nombrecontacto": "Juan Pérez",
  "correocontacto": "juan.perez@univez.com",
  "celularcontacto": "12345678",
  "usuario": {
    "id": 1
  },
  "sectorpertenencia": {
    "id": 3
  }
}

### PUT de Institucion
PUT http://{{host}}/institucion/2
Content-Type: application/json
Accept: application/json

{
  "nombreinstitucion": "Universidad ABC",
  "reseniainstitucion": "Descripción actualizada de la universidad.",
  "logoinstitucion": null, 
  "nombrecontacto": "María García",
  "correocontacto": "maria.garcia@universidadabc.com",
  "celularcontacto": "987654321",
  "usuario": {
    "id": 2
  },
  "sectorpertenencia": {
    "id": 1
  }
}

### DELETE de Institucion
DELETE http://{{host}}/institucion/3
Accept: application/json
