###SOLO SON DE REFERENCIA NO FUNCIONA SI DAS EL SEND REQUEST
###USAR POSTMAN o EXTENSION

POST localhost:3000/tipoUsuario/

Accept: application/json
Content-Type: application/json

{
    "tipo": "ola"
}

