@import ../settings.http
### GET ALL de Usuario
GET http://{{host}}/usuario/
Accept: application/json

### GET de Usuario
GET http://{{host}}/usuario/4
Accept: application/json

### POST de Usuario
POST http://{{host}}/usuario/
Content-Type: application/json
Accept: application/json

{
  "idusuario": "Quelof8",
  "contrasenia": "Cami",
  "tipousuario": {
    "id": 2
  }
}

### PUT de Usuario
PUT http://{{host}}/usuario/1
Content-Type: application/json
Accept: application/json

{
  "idusuario": "QuelitoMod",
  "contrasenia": "amnesia",
  "tipousuario": {
    "id": 3
  }
}

### DELETE de Usuario
DELETE http://{{host}}/usuario/2
Accept: application/json
